'use client';

import { useActionState, useState } from 'react';
import { approveImport, parseUpload, rollbackImport, validateUpload, type ImportActionState } from './actions';
import { IMPORT_SCHEMAS } from '@/lib/import/schema';
import type { ImportMode, ImportType } from '@/lib/import/types';

const initial: ImportActionState = { ok: false };
export default function ImportWizard() {
  const [parseState, parseAction] = useActionState(parseUpload, initial); const [validationState, validateAction] = useActionState(validateUpload, initial); const [importState, importAction] = useActionState(approveImport, initial); const [rollbackState, rollbackAction] = useActionState(rollbackImport, initial);
  const [type, setType] = useState<ImportType>('usage_history'); const [mode, setMode] = useState<ImportMode>('append'); const [mapping, setMapping] = useState<Record<string, string>>({}); const [replaceConfirmed, setReplaceConfirmed] = useState(false);
  const active = validationState.batchId ? validationState : parseState; const activeType = active.importType ?? type; const schema = IMPORT_SCHEMAS[activeType];
  const chosenMapping = Object.keys(mapping).length ? mapping : parseState.mapping ?? {};
  return <div className="analysis-page import-page">
    <div className="page-heading"><div><span className="eyebrow">DATA MANAGEMENT</span><h2>파일 적재</h2><p className="muted">RAW에 저장하기 전에 Preview와 Validation 결과를 확인합니다.</p></div></div>
    <section className="card section"><div className="card-title"><h3>1. 파일 선택 및 Import Type</h3><span>CSV / XLSX</span></div><form action={parseAction} className="import-form"><label>데이터 종류<select name="importType" value={type} onChange={(event) => setType(event.target.value as ImportType)}>{Object.entries(IMPORT_SCHEMAS).map(([key, item]) => <option key={key} value={key}>{item.label} ({key})</option>)}</select></label><label>Import Mode<select name="importMode" value={mode} onChange={(event) => setMode(event.target.value as ImportMode)}><option value="append">append</option><option value="upsert">upsert</option><option value="replace">replace</option></select></label><label>파일<input name="file" type="file" accept=".csv,.xlsx" required /></label><button className="button primary" type="submit">Parse 및 Preview</button></form>{parseState.message && <p className={parseState.ok ? 'text-good' : 'text-danger'}>{parseState.message}</p>}</section>
    {parseState.ok && parseState.batchId && <>
      <section className="card section"><div className="card-title"><h3>2. Column Mapping</h3><span>{parseState.totalRows}행</span></div><div className="mapping-grid">{schema.fields.map((field) => <label key={field.key}>{field.label}<select value={chosenMapping[field.key] ?? ''} onChange={(event) => setMapping((current) => ({ ...current, [field.key]: event.target.value }))}><option value="">매핑 안 함</option>{(parseState.headers ?? []).map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><form action={validateAction}><input type="hidden" name="batchId" value={parseState.batchId} /><input type="hidden" name="importType" value={activeType} /><input type="hidden" name="mapping" value={JSON.stringify(chosenMapping)} /><button className="button primary" type="submit">Validation 실행</button></form></section>
      <section className="card section"><div className="card-title"><h3>3. Preview</h3><span>첫 20행</span></div><p className="muted">원본 행은 staging에만 보관되며 Validation 전에는 RAW에 쓰이지 않습니다. Column Mapping을 최종 확인하세요.</p><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr>{(parseState.headers ?? []).slice(0, 8).map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{(parseState.preview ?? []).map((row, index) => <tr key={index}>{(parseState.headers ?? []).slice(0, 8).map((header) => <td key={header}>{String(row[header] ?? '')}</td>)}</tr>)}</tbody></table></div></section>
    </>}
    {validationState.batchId && <section className="card section"><div className="card-title"><h3>4. Validation Result</h3><span>{validationState.status}</span></div><div className="grid grid-3"><div><span className="metric-label">SUCCESS</span><div className="metric-value">{validationState.counts?.success ?? 0}</div></div><div><span className="metric-label">WARNING</span><div className="metric-value">{validationState.counts?.warning ?? 0}</div></div><div><span className="metric-label">ERROR</span><div className="metric-value">{validationState.counts?.error ?? 0}</div></div></div><p className={validationState.ok ? 'text-good' : 'text-danger'}>{validationState.message}</p><a className="button" href={`/api/admin/import/errors?batch_id=${encodeURIComponent(validationState.batchId)}`}>ERROR/WARNING CSV 다운로드</a></section>}
    {validationState.status === 'READY' && validationState.batchId && <section className="card section"><div className="card-title"><h3>5. 사용자 확인 및 Import</h3><span>승인된 행만 RAW 저장</span></div><p className="muted">replace는 기존 대상 테이블을 삭제하므로 확인을 체크해야 실행됩니다. replace 적재는 원복할 수 없습니다.</p><form action={importAction} className="button-row"><input type="hidden" name="batchId" value={validationState.batchId} /><input type="hidden" name="confirmReplace" value={mode === 'replace' && replaceConfirmed ? 'true' : 'false'} />{mode === 'replace' && <label><input type="checkbox" checked={replaceConfirmed} onChange={(event) => setReplaceConfirmed(event.target.checked)} /> 기존 대상 테이블을 삭제하고 replace합니다.</label>}<button className="button primary" type="submit" disabled={mode === 'replace' && !replaceConfirmed}>Import 승인</button></form>{importState.message && <p className={importState.ok ? 'text-good' : 'text-danger'}>{importState.message}</p>}</section>}
    {importState.status === 'IMPORTED' && importState.batchId && <section className="card section"><h3>6. Rollback</h3><form action={rollbackAction}><input type="hidden" name="batchId" value={importState.batchId} /><button className="button" type="submit">이 batch만 rollback</button></form>{rollbackState.message && <p>{rollbackState.message}</p>}</section>}
  </div>;
}
