import type { FieldSpec, ImportSchema, ImportType } from './types';

const field = (key: string, target: string, label: string, aliases: string[], type: FieldSpec['type'], extra: Partial<FieldSpec> = {}): FieldSpec => ({ key, target, label, aliases, type, ...extra });

export const IMPORT_SCHEMAS: Record<ImportType, ImportSchema> = {
  usage_history: { type: 'usage_history', label: '사용 이력', table: 'usage_history', fields: [field('usage_id', 'usage_id', '사용 이력 ID', ['usage_id', '사용이력ID', '사용ID'], 'text'), field('item_id', 'item_id', '품목코드', ['item_id', '품목코드', '품목 코드'], 'text', { required: true, relation: 'item' }), field('use_date', 'use_date', '사용일', ['use_date', '출고일', '사용일', '사용일자'], 'date', { required: true }), field('qty', 'qty', '수량', ['qty', '출고수량', '사용량', '수량'], 'number', { required: true, nonNegative: false }), field('warehouse', 'warehouse', '창고', ['warehouse', '창고'], 'text'), field('note', 'note', '비고', ['note', '비고', '메모'], 'text')] },
  inventory: { type: 'inventory', label: '재고', table: 'inventory', fields: [field('item_id', '품목코드', '품목코드', ['item_id', '품목코드', '품목 코드'], 'text', { required: true, relation: 'item' }), field('warehouse', '창고', '창고', ['warehouse', '창고'], 'text', { required: true }), field('current_stock', '현재고', '현재고', ['current_stock', '현재고', '재고'], 'number', { required: true, nonNegative: true }), field('as_of_date', '기준일자', '기준일자', ['as_of_date', '기준일자', '기준일'], 'date', { required: true }), field('safety_stock', '안전재고', '안전재고', ['safety_stock', '안전재고'], 'number', { nonNegative: true })] },
  item_master: { type: 'item_master', label: '품목 마스터', table: 'item_master', fields: [field('item_id', '품목코드', '품목코드', ['item_id', '품목코드'], 'text', { required: true }), field('item_name', '품목명', '품목명', ['item_name', '품목명'], 'text', { required: true }), field('item_type', '품목구분', '품목구분', ['item_type', '품목구분'], 'text'), field('unit', '단위', '단위', ['unit', '단위'], 'text'), field('standard_price', '표준단가', '표준단가', ['standard_price', '표준단가'], 'number', { nonNegative: true }), field('active', '사용여부', '사용여부', ['active', '사용여부'], 'text'), field('supplier_id', 'supplier_id', '공급업체코드', ['supplier_id', '공급업체코드'], 'text', { relation: 'supplier' })] },
  supplier_master: { type: 'supplier_master', label: '공급업체 마스터', table: 'supplier_master', fields: [field('supplier_id', '공급업체코드', '공급업체코드', ['supplier_id', '공급업체코드'], 'text', { required: true }), field('supplier_name', '공급업체명', '공급업체명', ['supplier_name', '공급업체명'], 'text', { required: true }), field('country', '국가', '국가', ['country', '국가'], 'text'), field('standard_lead_time', '표준리드타임(일)', '표준 리드타임', ['standard_lead_time', '표준리드타임', '표준리드타임(일)'], 'number', { nonNegative: true }), field('manager', '담당자', '담당자', ['manager', '담당자'], 'text'), field('active', '사용여부', '사용여부', ['active', '사용여부'], 'text')] },
  purchase_order: { type: 'purchase_order', label: '발주', table: 'purchase_order', fields: [field('po_id', '발주번호', '발주번호', ['po_id', '발주번호'], 'text', { required: true }), field('order_date', '발주일', '발주일', ['order_date', '발주일'], 'date', { required: true }), field('supplier_id', '공급업체', '공급업체', ['supplier_id', '공급업체', '공급업체코드'], 'text', { required: true, relation: 'supplier' }), field('item_id', '품목코드', '품목코드', ['item_id', '품목코드'], 'text', { required: true, relation: 'item' }), field('order_qty', '발주수량', '발주수량', ['order_qty', '발주수량'], 'number', { required: true, nonNegative: true }), field('unit_price', '단가', '단가', ['unit_price', '단가'], 'number', { nonNegative: true }), field('due_date', '납기예정일', '납기예정일', ['due_date', '납기예정일'], 'date'), field('owner', '발주담당', '발주담당', ['owner', '발주담당'], 'text')] },
  goods_receipt: { type: 'goods_receipt', label: '입고', table: 'goods_receipt', fields: [field('receipt_id', '입고번호', '입고번호', ['receipt_id', '입고번호'], 'text', { required: true }), field('po_id', '발주번호', '발주번호', ['po_id', '발주번호'], 'text'), field('item_id', '품목코드', '품목코드', ['item_id', '품목코드'], 'text', { required: true, relation: 'item' }), field('receipt_qty', '입고수량', '입고수량', ['receipt_qty', '입고수량'], 'number', { required: true, nonNegative: true }), field('receipt_date', '입고일', '입고일', ['receipt_date', '입고일'], 'date', { required: true }), field('warehouse', '입고창고', '입고창고', ['warehouse', '입고창고'], 'text')] },
  sales_order: { type: 'sales_order', label: '판매 주문', table: 'sales_order', fields: [field('sales_order_id', 'sales_order_id', '판매주문 ID', ['sales_order_id', '판매주문ID'], 'text', { required: true }), field('order_date', 'order_date', '주문일', ['order_date', '주문일'], 'date', { required: true }), field('customer_id', 'customer_id', '고객 ID', ['customer_id', '고객ID'], 'text'), field('item_id', 'item_id', '품목코드', ['item_id', '품목코드'], 'text', { required: true, relation: 'item' }), field('order_qty', 'order_qty', '주문수량', ['order_qty', '주문수량'], 'number', { required: true, nonNegative: true }), field('need_date', 'need_date', '필요일', ['need_date', '필요일'], 'date'), field('status', 'status', '상태', ['status', '상태'], 'text')] },
  business_event: { type: 'business_event', label: '업무 이벤트', table: 'business_event', fields: [field('event_id', 'event_id', '이벤트 ID', ['event_id', '이벤트ID'], 'text', { required: true }), field('item_id', 'item_id', '품목코드', ['item_id', '품목코드'], 'text', { relation: 'item' }), field('event_type', 'event_type', '이벤트 유형', ['event_type', '이벤트유형'], 'text', { required: true }), field('event_date', 'event_date', '이벤트일', ['event_date', '이벤트일'], 'date', { required: true }), field('qty', 'qty', '수량', ['qty', '수량'], 'number'), field('note', 'note', '비고', ['note', '비고'], 'text')] },
  item_substitute: { type: 'item_substitute', label: '대체 품목', table: 'item_substitute', fields: [field('item_id', 'item_id', '품목코드', ['item_id', '품목코드'], 'text', { required: true, relation: 'item' }), field('substitute_item_id', 'substitute_item_id', '대체 품목코드', ['substitute_item_id', '대체품목코드'], 'text', { required: true, relation: 'item' }), field('priority', 'priority', '우선순위', ['priority', '우선순위'], 'number', { nonNegative: true }), field('is_active', 'is_active', '활성 여부', ['is_active', '활성여부', '사용여부'], 'boolean')] },
};

export function getImportSchema(type: ImportType) { return IMPORT_SCHEMAS[type]; }
export function guessMapping(headers: string[], schema: ImportSchema): Record<string, string> {
  const normalized = (value: string) => value.trim().toLowerCase().replace(/[\s_\-]/g, '');
  const result: Record<string, string> = {};
  for (const spec of schema.fields) {
    const candidates = [spec.key, spec.target, spec.label, ...spec.aliases].map(normalized);
    const header = headers.find((candidate) => candidates.includes(normalized(candidate)));
    if (header) result[spec.key] = header;
  }
  return result;
}

